#!/usr/bin/env python3
"""PACT M4 — E9: does mesh coverage actually percolate?

The paper conjectures that with an instrumented fraction p, observation
"propagates transitively through multi-agent workflows" with "percolation
behavior above a graph-dependent threshold". This experiment tests that directly,
on random and scale-free interaction graphs, and reports what it finds rather
than what was hoped for.

Graphs and instrumentation are generated by hashing, not RNG, so every number
reproduces exactly. Signing cost was measured in E1; this measures graph
structure, so sessions here are counted rather than individually signed.

Run: ./.venv/bin/python3 e9.py
"""
from pactlog import H

N = 2000


def hrand(*parts) -> float:
    """Deterministic [0,1) from a hash of the parts."""
    return int.from_bytes(H("|".join(map(str, parts)).encode())[:6], "big") / float(1 << 48)


def er_graph(n=N, avg_deg=4.0, seed="er"):
    p = avg_deg / (n - 1)
    adj = {i: set() for i in range(n)}
    # sample candidate pairs sparsely: for each node, test a hashed neighbourhood
    for i in range(n):
        for j in range(i + 1, n):
            if hrand(seed, i, j) < p:
                adj[i].add(j); adj[j].add(i)
    return adj


def scale_free(n=N, m=2, seed="sf"):
    """Preferential attachment with deterministic, degree-weighted choice."""
    adj = {i: set() for i in range(n)}
    targets = [0, 1]
    adj[0].add(1); adj[1].add(0)
    repeated = [0, 1]
    for v in range(2, n):
        chosen = set()
        k = 0
        while len(chosen) < min(m, len(repeated)):
            pick = repeated[int(hrand(seed, v, k) * len(repeated))]
            chosen.add(pick)
            k += 1
        for t in chosen:
            adj[v].add(t); adj[t].add(v)
            repeated += [v, t]
    return adj


def edges(adj):
    return [(i, j) for i in adj for j in adj[i] if i < j]


def instrument_random(adj, p, seed="inst"):
    return {i for i in adj if hrand(seed, i) < p}


def instrument_hubs(adj, p):
    k = int(round(p * len(adj)))
    return set(sorted(adj, key=lambda i: (-len(adj[i]), i))[:k])


def coverage(adj, inst):
    e = edges(adj)
    observed = [(i, j) for i, j in e if i in inst or j in inst]
    no_endpoint = [1 for i, j in observed if i not in inst and j not in inst]
    uninst = [i for i in adj if i not in inst]
    exposed = [i for i in uninst if any(nb in inst for nb in adj[i])]
    return {
        "edges": len(e),
        "observed": len(observed),
        "edge_cov": len(observed) / len(e) if e else 0.0,
        "observed_without_instrumented_endpoint": sum(no_endpoint),
        "uninstrumented": len(uninst),
        "exposed": len(exposed),
        "exposure": len(exposed) / len(uninst) if uninst else 1.0,
    }


def walk_coverage(adj, inst, length=4, samples=2000, seed="walk"):
    """Multi-hop workflows: fraction with at least one observed hop, and fraction
    fully observed."""
    nodes = sorted(adj)
    any_obs = full_obs = total = 0
    for s in range(samples):
        cur = nodes[int(hrand(seed, s) * len(nodes))]
        hops, ok = [], True
        for h in range(length):
            nb = sorted(adj[cur])
            if not nb:
                ok = False
                break
            nxt = nb[int(hrand(seed, s, h) * len(nb))]
            hops.append((cur, nxt))
            cur = nxt
        if not ok or not hops:
            continue
        total += 1
        obs = [(a in inst or b in inst) for a, b in hops]
        any_obs += any(obs)
        full_obs += all(obs)
    return {"walks": total,
            "any_hop": any_obs / total if total else 0.0,
            "all_hops": full_obs / total if total else 0.0}


def main():
    print("\nE9 — mesh coverage on simulated interaction graphs\n")
    graphs = {"random (avg deg 4)": er_graph(), "scale-free (m=2)": scale_free()}

    for name, adj in graphs.items():
        e = edges(adj)
        degs = sorted((len(adj[i]) for i in adj), reverse=True)
        print(f"{name}: {len(adj)} agents, {len(e)} interactions, "
              f"max degree {degs[0]}, median {degs[len(degs) // 2]}")

    print("\n1. Edge coverage versus instrumented fraction p (random instrumentation)")
    print("   p       random graph        scale-free        predicted 1-(1-p)^2")
    for p in (0.01, 0.05, 0.10, 0.25, 0.50):
        row = []
        for name, adj in graphs.items():
            c = coverage(adj, instrument_random(adj, p))
            row.append(c["edge_cov"])
        print(f"   {p:.2f}    {row[0]:>10.3f}        {row[1]:>10.3f}        "
              f"{1 - (1 - p) ** 2:>14.3f}")
    print("   The pairwise formula tracks the random graph closely for p >= 0.05; at")
    print("   p = 0.01 only ~20 agents are instrumented, so the draw is noisy. The")
    print("   scale-free graph sits consistently BELOW the formula: degree there is")
    print("   highly skewed (median 2, max 86), so a uniformly random pick almost always")
    print("   lands on a low-degree agent and buys less coverage than the uniform-degree")
    print("   prediction. Realistic topology makes random instrumentation worse, not")
    print("   better — which is what makes hub-first instrumentation necessary, not just")
    print("   efficient.")

    print("\n2. Instrumenting hubs instead of random nodes (the chokepoint strategy)")
    print("   p       random pick    hubs first    coverage multiple")
    for p in (0.01, 0.02, 0.05, 0.10):
        adj = graphs["scale-free (m=2)"]
        r = coverage(adj, instrument_random(adj, p))["edge_cov"]
        h = coverage(adj, instrument_hubs(adj, p))["edge_cov"]
        print(f"   {p:.2f}    {r:>10.3f}    {h:>10.3f}    {h / r if r else 0:>13.1f}x")
    print("   Instrumenting the top 1% by degree covers 22% of all interactions — the")
    print("   coverage random instrumentation needs roughly 12% of agents to reach. It")
    print("   does NOT beat instrumenting half the graph at random (0.74); the claim is")
    print("   efficiency per agent instrumented, not absolute reach. This is the coverage")
    print("   pyramid of §VIII in graph terms, and why Tier A is ~10 organizations.")

    print("\n3. Does observation propagate? (the percolation conjecture)")
    print("   p      edge coverage   d(coverage)/dp   edges observed with NO")
    print("                                            instrumented endpoint")
    adj = graphs["scale-free (m=2)"]
    prev = None
    for p in (0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40):
        c = coverage(adj, instrument_random(adj, p))
        d = "" if prev is None else f"{(c['edge_cov'] - prev) / 0.05:>13.2f}"
        print(f"   {p:.2f}   {c['edge_cov']:>13.3f}   {d:>14}   "
              f"{c['observed_without_instrumented_endpoint']:>20}")
        prev = c["edge_cov"]

    print("\n4. Multi-hop workflows (4 hops, scale-free)")
    print("   p      >=1 hop observed   all hops observed")
    for p in (0.05, 0.10, 0.25, 0.50):
        w = walk_coverage(adj, instrument_random(adj, p))
        print(f"   {p:.2f}   {w['any_hop']:>16.3f}   {w['all_hops']:>17.3f}")

    print("\n5. Agent exposure by degree: uninstrumented agents with at least one")
    print("   instrumented counterparty (scale-free, p = 0.10)")
    print("   degree band    agents    exposed    share")
    inst = instrument_random(adj, 0.10)
    bands = [(1, 2), (3, 5), (6, 15), (16, 10**6)]
    for lo, hi in bands:
        grp = [i for i in adj if i not in inst and lo <= len(adj[i]) <= hi]
        exp = [i for i in grp if any(nb in inst for nb in adj[i])]
        label = f"{lo}-{hi}" if hi < 10**6 else f"{lo}+"
        share = len(exp) / len(grp) if grp else 0.0
        print(f"   {label:<13}  {len(grp):>6}    {len(exp):>7}    {share:>5.3f}")
    print("   Exposure is 1-(1-p)^degree, so it is not uniform across the population:")
    print("   at the same p, degree-16+ agents are five times more exposed than")
    print("   degree-1-2 agents (0.86 versus 0.17). The agents hardest to keep")
    print("   unobserved are precisely the heavily-used ones.")

    print("\n  VERDICT ON THE CONJECTURE — it does not hold, and should be withdrawn.")
    print("  Two kinds of evidence, kept separate because they carry different weight:")
    print()
    print("  DEFINITIONAL (proves the mechanism, measures nothing): the count of edges")
    print("  observed without an instrumented endpoint is 0 for ANY graph at ANY p,")
    print("  because coverage() defines 'observed' as having such an endpoint. This")
    print("  follows from the design — an instrumented agent records its own")
    print("  interactions and nothing further — and needed no simulation. It is stated")
    print("  here as a design property, not offered as a result.")
    print()
    print("  EMPIRICAL (could have come out otherwise): there is no threshold and no phase")
    print("  transition: the derivative stays inside a narrow band (~1.1-1.9, the")
    print("  scatter being sampling noise from an independent draw at each p) rather")
    print("  than spiking, which is what a percolation threshold would produce.")
    print("  Multi-hop workflows confirm it: 'all hops observed' stays far below")
    print("  '>=1 hop observed', so a workflow is typically seen in fragments.")
    print()
    print("  What replaces it is more useful for the paper's actual argument. Coverage")
    print("  is DEGREE-WEIGHTED, not viral: an agent is exposed with probability")
    print("  1-(1-p)^degree, so at p=0.10 the busiest agents are five times more exposed")
    print("  than the quietest, and the agents that matter most - popular tools and")
    print("  services - are the hardest to keep dark. Instrumenting the top 1% by degree")
    print("  buys the coverage that ~12% random instrumentation would. The mesh's value")
    print("  is efficiency at chokepoints, not propagation.")


if __name__ == "__main__":
    main()
